### ISSUE TITLE
MemoryManager seems to copy freeRTOS memory - micro_ROS:Humble

### ISSUE THREAD

**Issue by luukWeFab** [micro-ROS/micro_ros_stm32cubemx_utils#122]
Hey, I noticed that when I increase the TOTAL_HEAP_SIZE variable for freeRTOS in STM32cubeMX that my RAM memory consumption would increase by roughly double the amount. After analyzing my .map file with amap I noticed that the custom_memory_manager.o uses just as much memory as the heap_4.o file. For example with the following settings in STM32CubeMX 
![image](https://github.com/micro-ROS/micro_ros_stm32cubemx_utils/assets/143802674/88d63540-d996-4a74-8f1e-645ce92617ab)
I get the following memory map for the custom_memory_manager, and heap_4 file. 
![image](https://github.com/micro-ROS/micro_ros_stm32cubemx_utils/assets/143802674/cb7618af-0c64-49a0-9c50-521c8aac3cbd)

Setting the TOTAL_HEAP_SIZE to 14000 bytes as follows:
![image](https://github.com/micro-ROS/micro_ros_stm32cubemx_utils/assets/143802674/55adb529-0f22-4a7f-be44-0ebd77e023fd)
Results in the following map
![image](https://github.com/micro-ROS/micro_ros_stm32cubemx_utils/assets/143802674/fd743370-16d0-4b4b-b8fa-4d164f2b436a)

This leads me to believe that the memory manager allocates the same room as FreeRTOS but creates its own heap for that, which is what I found in custom_memory_manager.c. I was wondering whether this is intentional or whether the memory manager was supposed to reserve its heapspace in the heap of the FreeRTOS heap?

**Comment by pablogs9** [comment]
This memory manager intends to replace heap4.c

**Comment by luukWeFab** [comment]
But then I would have to alter the FreeRTOS  library to include that rather than heap4.c. So wouldn't that break if I regenerated the code using STM32CubeMX?

**Comment by pablogs9** [comment]
You can tune both heap4.c and custom_memory_manager.c to have the size according to your requirements, taking into account that the first one will be used by your system and the second will be used by micro-ROS.

They shall not collide since the one we provide has the function suffixed with "MicroROS".

In general, you can find more info about micro-ROS allocators here: https://docs.vulcanexus.org/en/latest/rst/tutorials/micro/memory_management/memory_management.html

**Comment by luukWeFab** [comment]
Ahh okay, thanks for the help.
